all_test.go, auth.go, config.go, db.go, db_sql.go, ldap.go
Implemented ldap merge poller, merging ldap users into imqs for authorization when ldap delegated for authentication
=> Implemented ldap merge poller

config.go, frontends.go
Changes for port variations in configuration.
=> ITOOLS-404 Support for Docker

all_test.go, auth.go, db.go, db_sql.go
=>   TI-2402 - User list Filter

db.go
=> Fix: TestArchiveIdentity test broken

auth.go
=> TI-2400 - Audit Trail - Access logging

all_test.go, auth.go, frontends.go
=> TI-2400 - Log user changes audit actions

auth.go
=> Fix for TI-2400 - Remove action type field

auth.go
=> Fix: Ldap users session expires immediately.

db_sql.go
=> TI-3035 - Unable to Reset UAT password

auth.go
=> TI-3017 - Rename audit actions to make them generic

all_test.go, auth.go, ldap.go
=> TI-3140 - Log changes to Ldap users to user audit trail and add missing details

auth.go
=> TI-3417 - Add 'Failed Login' audit action

all_test.go, auth.go, config.go, db.go, db_sql.go, frontends.go
- Lock account after 3 login attempts
- Save account locked status in DB
=> TI-3416 - Lock account after 3 failed login attempts

auth.go
=> TI-3417 - Report on Failed Logins in Audit Log

auth.go, go.mod, go.sum, msaad.go, roledb.go
- Remove the concept of the EssentialRoles from IMQS
- Create the concept of the DefaultRoles for IMQS
- Attempt to add experimental configuration to support automatic
detection of permissions that are designed to be relevant to to an IMQS
instance
=> Expanding the MSAAD authentication for DTPW clients

dummyRoleGroupDB.go, roledb.go
Get raw groups from db for export groups (and users in groups) to json
=> INF-1305 export user groups json

all_test.go, auth.go, db.go, db_sql.go, ldap.go, msaad.go, oauth.go
This is a fix for https://imqssoftware.atlassian.net/browse/INF-1369
The two commits contain detailed comments. I have tested this by manually fudging my DB, but haven't tested it with a real LDAP integration.
=> Fix incorrect "Modified By" field on user permissions config page

roledb.go
Add Diff function to PermissionList
=> Add Diff function to PermissionList

msaad.go
Correct an oversight in the MSAAD synchronisation process where the username was not populated, neither with the email (as in the OAuth flow) nor with the UserPricipalName.
=> ASG-1882 : Add username update to MSAAD synch

oauth.go
Passthrough auth never created oauth sessions since it relied on entries in oauthchallenge. It appeared to work for a while after login because there were normal sessions created in authsession, which quickly got expired on the next token refresh from MSAAD (no matching oauthsession).
=> BAZ-202 : Fix passthrough auth session bug.

auth.go, msaad.go, utils.go
=> Harden MSAAD sync (ASG-3350)

auth.go, db.go, db_sql.go, dummyUserStore.go, migrations.go
Add the Termination date, Last Login date, Disabled date and Enabled date to the "User List" export. 
refs: NEXUS-4245
=> Add new columns under "User List" exports
